language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t nanda1505/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true nanda1505/react-test npm test

after_success:
  - docker build -t nanda1505/multi-client ./client
  - docker build -t nanda1505/multi-nginx ./nginx
  - docker build -t nanda1505/multi-server ./server
  - docker build -t nanda1505/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take the images and push them docker hub
  - docker push nanda1505/multi-client
  - docker push nanda1505/multi-nginx
  - docker push nanda1505/multi-server
  - docker push nanda1505/multi-worker
